### PR TITLE
Exit when job uri is invalid.

### PR DESCRIPTION
**Pull request by phile314**
With this change, Hail will exit if an invalid URI is given. It still retries for all other errors like e.g. timeouts etc.

### CODE REVIEW

**Comment by phile314** [comment]
See https://github.com/TaktInc/hail/issues/11

**Comment by shlevy** [comment]
What will the error message look like here?

**Comment by phile314** [comment]
Still the same as before:
```
hail: InvalidUrlException "sdf/latest" "Invalid URL"
```
Exit status code is 1 in this case.

**Comment by shlevy** [comment]
@phile314 Added you to committers, feel free to merge this.

**Comment by phile314** [comment]
Thank you, done!

**Pull request merged**
